// @file: /pages/brewcommand/index.js
// @summary: Route entry point for the BrewCommand cockpit
// @timestamp: autogenerated by Brew Da RouterSynth 🧠⚙️

export { default } from './CommandConsolePage';