"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INGESTION_SOURCES = void 0;
exports.getSourceConfig = getSourceConfig;
exports.getSourcesByState = getSourcesByState;
exports.getSourcesByGame = getSourcesByGame;
exports.INGESTION_SOURCES = {
    // North Carolina - Official CSV sources (highest trust)
    nc_pick3_official: {
        sourceKey: 'nc_pick3_official',
        state: 'NC',
        game: 'pick3',
        sourceName: 'NC Lottery Official',
        sourceUrl: 'https://nclottery.com/pick3-past-draws',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official NC CSV download',
    },
    nc_pick4_official: {
        sourceKey: 'nc_pick4_official',
        state: 'NC',
        game: 'pick4',
        sourceName: 'NC Lottery Official',
        sourceUrl: 'https://nclottery.com/pick4-past-draws',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official NC CSV download',
    },
    nc_cash5_official: {
        sourceKey: 'nc_cash5_official',
        state: 'NC',
        game: 'cash5',
        sourceName: 'NC Lottery Official',
        sourceUrl: 'https://nclottery.com/cash5-past-draws',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official NC page',
    },
    nc_powerball_official: {
        sourceKey: 'nc_powerball_official',
        state: 'NC',
        game: 'powerball',
        sourceName: 'NC Lottery Official',
        sourceUrl: 'https://nclottery.com/powerball-past-draws',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official NC CSV download',
    },
    nc_mega_official: {
        sourceKey: 'nc_mega_official',
        state: 'NC',
        game: 'mega_millions',
        sourceName: 'NC Lottery Official',
        sourceUrl: 'https://nclottery.com/mega-millions-past-draws',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official NC CSV download',
    },
    // California - Official page parsers
    ca_daily3_official: {
        sourceKey: 'ca_daily3_official',
        state: 'CA',
        game: 'daily3',
        sourceName: 'California Lottery Official',
        sourceUrl: 'https://www.calottery.com/en/draw-games/daily-3',
        sourceType: 'official-page',
        sourceTier: 1,
        trustScore: 90,
        isActive: true,
        notes: 'Official CA page parse',
    },
    ca_daily4_official: {
        sourceKey: 'ca_daily4_official',
        state: 'CA',
        game: 'daily4',
        sourceName: 'California Lottery Official',
        sourceUrl: 'https://www.calottery.com/en/draw-games/daily-4',
        sourceType: 'official-page',
        sourceTier: 1,
        trustScore: 90,
        isActive: true,
        notes: 'Official CA page parse',
    },
    ca_fantasy5_official: {
        sourceKey: 'ca_fantasy5_official',
        state: 'CA',
        game: 'fantasy5',
        sourceName: 'California Lottery Official',
        sourceUrl: 'https://www.calottery.com/en/draw-games/fantasy-5',
        sourceType: 'official-page',
        sourceTier: 1,
        trustScore: 90,
        isActive: true,
        notes: 'Official CA page parse',
    },
    // California - Historical archive sources
    ca_daily3_history: {
        sourceKey: 'ca_daily3_history',
        state: 'CA',
        game: 'daily3',
        sourceName: 'Lottery Extreme Archive',
        sourceUrl: 'https://www.lotteryextreme.com/california/daily3-detailed_results',
        sourceType: 'trusted-archive',
        sourceTier: 2,
        trustScore: 75,
        isActive: true,
        notes: 'Historical backfill - cross-check with official',
    },
    ca_daily4_history: {
        sourceKey: 'ca_daily4_history',
        state: 'CA',
        game: 'daily4',
        sourceName: 'Lottery Extreme Archive',
        sourceUrl: 'https://www.lotteryextreme.com/california/daily4-detailed_results',
        sourceType: 'trusted-archive',
        sourceTier: 2,
        trustScore: 75,
        isActive: true,
        notes: 'Historical backfill - cross-check with official',
    },
    ca_fantasy5_history: {
        sourceKey: 'ca_fantasy5_history',
        state: 'CA',
        game: 'fantasy5',
        sourceName: 'Lottery Extreme Archive',
        sourceUrl: 'https://www.lotteryextreme.com/california/fantasy5-detailed_results',
        sourceType: 'trusted-archive',
        sourceTier: 2,
        trustScore: 75,
        isActive: true,
        notes: 'Historical backfill - cross-check with official',
    },
    // Multi-state games
    powerball_official: {
        sourceKey: 'powerball_official',
        state: 'MULTI',
        game: 'powerball',
        sourceName: 'Powerball Official',
        sourceUrl: 'https://www.powerball.com/',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official multi-state source',
    },
    mega_millions_official: {
        sourceKey: 'mega_millions_official',
        state: 'MULTI',
        game: 'mega_millions',
        sourceName: 'Mega Millions Official',
        sourceUrl: 'https://www.megamillions.com/',
        sourceType: 'official',
        sourceTier: 1,
        trustScore: 100,
        isActive: true,
        notes: 'Official multi-state source',
    },
};
function getSourceConfig(sourceKey) {
    return exports.INGESTION_SOURCES[sourceKey];
}
function getSourcesByState(state) {
    return Object.values(exports.INGESTION_SOURCES).filter(function (s) { return s.state === state; });
}
function getSourcesByGame(game) {
    return Object.values(exports.INGESTION_SOURCES).filter(function (s) { return s.game === game; });
}
