import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { analyzeEntropy } from '@/lib/audit/entropyTools'; // optional helper
import { getAiRuntimeConfig } from "@/lib/ai/client";
import { estimateAiUsageCostUsd, recordAiUsageEvent } from '@/lib/ai/usage';

export async function POST(req: Request) {
    const { path: filePath, code: overrideCode } = await req.json();

    if (!filePath) {
        return NextResponse.json({ error: 'Missing file path' }, { status: 400 });
    }

    try {
        const ai = getAiRuntimeConfig();
        if (!ai) {
            return NextResponse.json(
                { error: "No AI provider credentials are configured." },
                { status: 500 }
            );
        }

        const fullPath = path.join(process.cwd(), 'public', filePath);
        const rawCode = overrideCode || fs.readFileSync(fullPath, 'utf-8');
        const startedAt = Date.now();

        // (Optional) Perform pre-analysis
        const entropyReport = analyzeEntropy?.(rawCode);

        // 👇 Brew AI fix prompt (abstracted here)
        const completion = await ai.client.chat.completions.create({
            model: ai.model,
            messages: [
                {
                    role: 'system',
                    content: 'You are Brew Da AI, a helpful assistant focused on clean, readable, and resilient JavaScript.'
                },
                {
                    role: 'user',
                    content: `Here is some JS code from a file called ${filePath}. Suggest a patch with brief reasoning. Only suggest changes if they're meaningful.\n\n${rawCode}`
                }
            ]
        });

        const { choices } = completion;
        const aiReply = choices?.[0]?.message?.content || '';
        const usageSnapshot = estimateAiUsageCostUsd(ai.provider, ai.model, completion.usage);

        void recordAiUsageEvent({
            route: '/api/suggest-fix',
            operation: 'code_suggestion',
            provider: ai.provider,
            model: ai.model,
            status: 'success',
            latencyMs: Date.now() - startedAt,
            inputTokens: usageSnapshot.inputTokens,
            outputTokens: usageSnapshot.outputTokens,
            totalTokens: usageSnapshot.totalTokens,
            estimatedCostUsd: usageSnapshot.estimatedCostUsd,
            metadata: {
                filePath,
                entropyScore: entropyReport?.score ?? null,
            },
        }).catch((logError) => {
            console.error('AI usage log error:', logError);
        });

        return NextResponse.json({
            suggestion: aiReply,
            reason: 'Generated by Brew AI assistant',
            entropy: entropyReport || null
        }, { status: 200 });
    } catch (err: any) {
        console.error('[suggest-fix]', err);

        const ai = getAiRuntimeConfig();
        if (ai) {
            void recordAiUsageEvent({
                route: '/api/suggest-fix',
                operation: 'code_suggestion',
                provider: ai.provider,
                model: ai.model,
                status: 'error',
                errorMessage: err instanceof Error ? err.message : 'Unknown AI error',
                metadata: {
                    filePath,
                },
            }).catch((logError) => {
                console.error('AI usage log error:', logError);
            });
        }

        return NextResponse.json({ error: 'Unable to analyze file' }, { status: 500 });
    }
}
