import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { analyzeEntropy } from '@/lib/audit/entropyTools'; // optional helper

export async function POST(req: Request) {
    const { path: filePath, code: overrideCode } = await req.json();

    if (!filePath) {
        return NextResponse.json({ error: 'Missing file path' }, { status: 400 });
    }

    try {
        const fullPath = path.join(process.cwd(), 'public', filePath);
        const rawCode = overrideCode || fs.readFileSync(fullPath, 'utf-8');

        // (Optional) Perform pre-analysis
        const entropyReport = analyzeEntropy?.(rawCode);

        // 👇 Brew AI fix prompt (abstracted here)
        const response = await fetch('https://api.openai.com/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: 'gpt-4',
                messages: [
                    {
                        role: 'system',
                        content: 'You are Brew Da AI, a helpful assistant focused on clean, readable, and resilient JavaScript.'
                    },
                    {
                        role: 'user',
                        content: `Here is some JS code from a file called ${filePath}. Suggest a patch with brief reasoning. Only suggest changes if they're meaningful.\n\n${rawCode}`
                    }
                ]
            })
        });

        const { choices } = await response.json();
        const aiReply = choices?.[0]?.message?.content || '';

        return NextResponse.json({
            suggestion: aiReply,
            reason: 'Generated by Brew AI assistant',
            entropy: entropyReport || null
        }, { status: 200 });
    } catch (err: any) {
        console.error('[suggest-fix]', err);
        return NextResponse.json({ error: 'Unable to analyze file' }, { status: 500 });
    }
}
